# Generated by Django 5.1.1 on 2026-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_booking_user_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='seat_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
